### ISSUE TITLE
Cannot install properly

### ISSUE THREAD

**Issue by rvetere** [tim-field/graphql-wp#10]
Hi there,

i followed the step in the readme:

`composer require mohiohio/graphql-wp`

i can see the lib and all the dependencies in my "vendor" folder. i also added the entries proposed to my "composer.json" with the installer-paths for the plugins.

but even after a re-install, i can't see any entries to my "wp-content/plugins" folder - also no "/graphql" endpoint is there when i startup.. but ok i guess the basic install of the plugin into wordpress is missing..

how should this work properly?

**Comment by tim-field** [comment]
Make sure you are telling composer where it should put dependancies of type `wordpress-plugin`

So your composer will need a section such as this

```
"extra" : {
        "wordpress-install-dir": "public/wp",
        "installer-paths": {
            "public/wp-content/plugins/{$name}/": ["type:wordpress-plugin"],
            "public/wp-content/themes/{$name}/": ["type:wordpress-theme"]
        }
    },
```

Where `public/wp-content/plugins/{$name}/` is the path to your plugins directory. 

You will also need something like `require_once(dirname(__DIR__) . '/vendor/autoload.php');` somewhere in your project, inside wp-config.php for example 

I'd highly recommend taking a look at roots https://roots.io/bedrock/ for a nice composer enabled wordpress setup. ( if you used this then you could just do a `composer require mohiohio/graphql-wp` as they have already taken care of everything else )

**Comment by rvetere** [comment]
Thanks for the fast reply! Yes somehow i was still pretty far away from a working composer setup for wordpress.

This "roots bedrock" repo is totally awesome! Now i was pretty fast getting to the point where i have the files in question at the right place:

![files](https://photos-5.dropbox.com/t/2/AADL6roTappCJ6RfSUWwoj4lgaaUieV63ftsYWtoanM1uQ/12/4549844/png/32x32/3/1477944000/0/2/Screenshot%202016-10-31%2016.19.28.png/EPDXtAMYyMkoIAcoBw/_KsTKlZEoTs62cuD8ckA4pewFDkzA2CEYZ6Dnibu-Dw?size_mode=3&dl=0&size=2048x1536)

Now when i enter the admin area of the wordpress instance - i just don't see it yet as an installed plugin. So, i'll check again the readmes/documentations of everything to find out how to actually install it now 😉
