### ISSUE TITLE
No endpoint available

### ISSUE THREAD

**Issue by rvetere** [tim-field/graphql-wp#12]
Wow i finally did it to successfully install the plugin, but now i don't have any endpoint "/graphql" available.. 😕 

My docker-setup runs smoothly on "http://192.168.99.100/web" - showing up with the wordpress landing page on this domain.. so i thought it must be "http://192.168.99.100/web/graphql" now to access it, but i only get 404 back, whatever combo i try...

How can i debug this further down?

**Comment by luandro** [comment]
Whenever I try querying, for example:

```
 {"query":"{ 
        wp_query { 
            posts(paged: 1 posts_per_page: 10)  { 
                title 
                name 
                terms (taxonomy:\"category\") { 
                    name 
                    slug 
                }
            }
        }
    }"}
```

I get: 

```
{
  "data": null,
  "errors": [
    {
      "message": "Syntax Error GraphQL request (1:2) Expected Name, found String \"query\"\n\n1: {\"query\":\n    ^\n2:     \"{ wp_query \n",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ]
    }
  ]
}
```

Is there something wrong?

**Comment by rvetere** [comment]
And how did you got the endpoint working? I can see that it's based on the `Router` class, also coming from `Mohiohio`... so i found out it is dependent on the other lib "mohiohio/wordpress-lib" (cool for _not_ mentioning that 😛 ).... ok, well at least composer installed it anyways... 

ok, now.. as i slowly get insane with this s**\* ... going down step by step... is the "index.php" called within the plugin folder?
- added a stupid "var_dump('hello')" to the index.php just before the Router::routes call... ok i get there
- is the "Router" constant defined? well a simple "var_dump(Router)" means, no constant defined... mhm ok
- do i get into the "routes" call? Well yes, seems so.... strange when the constant is not defined...

-> i even get into the internal Call of "Router" himself.. wow... seems like it works..

BUT, still no working endpoint...

**Comment by tim-field** [comment]
Have you got permalinks enabled in WordPress settings?

**Comment by luandro** [comment]
@tim-field what do you mean?

**Comment by tim-field** [comment]
https://codex.wordpress.org/Using_Permalinks

**Comment by luandro** [comment]
But what should the settings be?

**Comment by tim-field** [comment]
before you even try to get this working you should be able to load a post with its slug name

mysite.com/hello-world

where hello-world is the slug name of a post. This is what the permalinks setting does. This is general WordPress setup stuff that you'll need to be familiar with before using a plugin like this. Plenty of resources online will get you this far.

If you can't get that working you aren't going to be able to use this library. 

Once you've got that working you can try enabling this plugin, and you'll then be able to get the the graphql/ endpoint.

**Comment by rvetere** [comment]
WOa thx a lot @tim-field -> the thing with the permalinks was exactly the missing piece in my setup! now this is just part of my repo and docs so it can't get lost again in my project... in the meantime i tried out an apollo-server approach, accessing directly the wordpress mysql db... but this was pretty fugly... now i look forward with your approach to reach my goals!

**Comment by tim-field** [comment]
@rvetere nice :) 

Yes I've used this with apollo redux graphql setup and it worked well, so you should be good :)
