### ISSUE TITLE
Taxonomy Parameters?

### ISSUE THREAD

**Issue by ghost** [tim-field/graphql-wp#17]
First, thanks for such useful and wonderful plugin!

Do you have plans to add [Taxonomy Parameters](https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters) for wp_query? 

I tried to add this possibility, but fails to make the data type needed for wordpress.
```php
$args = array(
	'post_type' => 'post',
	'tax_query' => array(
		'relation' => 'AND',
		array(
			'taxonomy' => 'movie_genre',
			'field'    => 'slug',
			'terms'    => array( 'action', 'comedy' ),
		),
		array(
			'taxonomy' => 'actor',
			'field'    => 'term_id',
			'terms'    => array( 103, 115, 206 ),
			'operator' => 'NOT IN',
		),
	),
);
```

**Comment by tim-field** [comment]
Very good question.

This is actually a bit difficult to implement as a parameter as its recursive, and generally quite a weird shape. Until I work out how to do it you can add something like this to the wp_query node

```php
use GraphQL\Type\Definition\ListOfType;
use GraphQL\Type\Definition\Type;
use Mohiohio\GraphQLWP\Type\Definition\Post;

// ...

// We are extending the fields in the wp_query node

add_filter('graphql-wp/get_wp_query_schema', function($schema) {

    $schema['fields'] = function() use ($schema) {

        return $schema['fields']() + [
            'posts_by_movie' => [
                'type' => new ListOfType(Post::getInstance()),
                'args' => [
                    'movie_slugs' => [
                        'type' => new ListOfType(Type::string()),
                    ]
                ],
                'resolve' => function($root, $args) {
                    $resolve['post_type'] = 'post';
                    $resolve['tax_query'] = [
                        [
                            'taxonomy' => 'movie_genre',
                            'field' => 'slug',
                            'terms' => $args['movie_slugs']
                        ]
                    ];
                    return get_posts($resolve);
                }
            ]
        ];
    };
    return $schema;
});

```

This should give you something like

![image](https://cloud.githubusercontent.com/assets/1326910/22543943/ae9d4104-e997-11e6-9cab-93c13b3254dd.png)

**Comment by tim-field** [comment]
Oh also if you do the above, grab the lastest release `0.4.3`.  As I just noticed that filter had the rather ugly name of `graphql-wp/get_w_p_query_schema` and this has now been renamed to the nicer `graphql-wp/get_wp_query_schema`  as above

**Comment by ghost** [comment]
Thank you very much. I will try today!

**Comment by tim-field** [comment]
FYI I'm also doing something similar here ( https://github.com/tim-field/graphql-wp/blob/master/Type/Definition/WPQuery.php#L78 ) to enable query products by product categories
