### ISSUE TITLE
Returning children for terms

### ISSUE THREAD

**Issue by ghost** [tim-field/graphql-wp#2]
Hi @timbofield 

There is an option to return children for `terms` using the following args: `parent` or `child_of`.
It is fine, but I want to return information about parent and children in the same roundtrip.

So as to do that I added the following field to `WP_Term`:

```
           'children' => [
                    'type' => new ListOfType($this->getTerm()),
                    'description' => 'retrieves children of the term',
                    'resolve' => function($root, $args) {

                        $childrenIds = get_term_children($root->term_id, $root->taxonomy);

                        return get_terms($root->taxonomy, array('include' => $childrenIds));
                    }
                ]
```

Unfortunately, it does not work and I do not why. There is no any error in logs. In Chromeiql I receive only:

```
TypeError: Failed to fetch
    at TypeError (native)
```

Do you know maybe why?
Did you have such problems? How did you resolve them?
Cheers.

**Comment by ghost** [comment]
As the type of children is actually the type of parent, there might be an infinite loop.
Do you know how to create recursive nested objects using [graphql-php](https://github.com/webonyx/graphql-php)?

**Comment by tim-field** [comment]
Sorry I missed this until now.

Just pushed  a53cb55 which seems to get it working 

Note that the type is defined in a callback, this prevents an infinite loop during type definition.
