### ISSUE TITLE
Advanced custom fields - repeater - galleries and flexible content

### ISSUE THREAD

**Issue by tonihaupt** [tim-field/graphql-wp#22]
Are the re some hints how to integrate those fieldtypes into our graphql schema or somebody has already done that?

**Comment by roryheaney** [comment]
@tonihaupt did you figure this out?

**Comment by tim-field** [comment]
See https://github.com/tim-field/graphql-wp#custom-fields using ACF isn't any different really, just use ACF's field types, and resolve to something that makes sense.

Types for ACF images and files are already defined, and might be helpful here 
https://github.com/tim-field/graphql-wp/blob/master/Type/Definition/ACFImage.php
