### ISSUE TITLE
A regular WP plugin

### ISSUE THREAD

**Issue by mayankguptadotcom** [tim-field/graphql-wp#23]
Hey Tim, Just wondering if you're planning to release it as a regular WordPress plugin with its dependencies etc. packaged as a normal WP plugin?

**Comment by paomosca** [comment]
+1

**Comment by tonihaupt** [comment]
@tim-field is this still maintained. I think the way to make it regular plugin will dig it's way through the community. If you need help add me as contributor. Working right now on implementing all Advanced Custom fields to the graphql endpoint and working with your plugin on our vue wordpress graphql course. Would be great to hear from you.

**Comment by tim-field** [comment]
I'd be really keen to merge any pull requests, if these look good then I can add you as a contributor.

I'm reluctant to add this as an official plugin, as you need to be a developer to use it, so it's likely to just confuse most people.  Not to mention getting a package to the plugin directory requires messing with subversion clunk.

https://roots.io/using-composer-with-wordpress/

If you aren't using composer with WordPress you're doing it wrong. :package:
