### ISSUE TITLE
Problem with custom post type query

### ISSUE THREAD

**Issue by cctoni** [tim-field/graphql-wp#24]
Heyho its me toni again, new account :P
when i call a query { wp_query { posts(post_type: "offers") { title } } } i get the following error.

"message": "Abstract type WPPost must resolve to an Object type at runtime for field WPQuery.posts with value \"WP_Post Object\n(\n    [ID] => 11\n    [post_author] => 1\n    [post_date] => 2017-05-04 15:04:18\n    [post_date_gmt] => 2017-05-04 13:04:18\n    [post_content] => <ul>\r\n \t<li>Wir sind die Bulletlist für dieses Angebot</li>\r\n \t<li>Wir sind die Bulletlist für dieses Angebot</li>\r\n \t<li>Wir sind die Bulletlist für dieses Angebot</li>\r\n \t<li>Wir sind die Bulletlist für dieses Angebot</li>\r\n \t<li>Wir sind die Bulletlist für dieses Angebot</li>\r\n</ul>\n    [post_title] => This is the first offer\n    [post_excerpt] => \n    [post_status] => publish\n    [comment_status] => closed\n    [ping_status] => closed\n    [post_password] => \n    [post_name] => this-is-the-first-offer\n    [to_ping] => \n    [pinged] => \n    [post_modified] => 2017-05-04 15:43:30\n    [post_modified_gmt] => 2017-05-04 13:43:30\n    [post_content_filtered] => \n    [post_parent] => 0\n    [guid] => http://remindme.dev/?post_type=offers&#038;p=11\n    [menu_order] => 0\n    [post_type] => offers\n    [post_mime_type] => \n    [comment_count] => 0\n    [filter] => raw\n)\n\",received \"\"."

**Comment by tim-field** [comment]
Gosh sorry, this is fixed in 0.4.4
