### ISSUE TITLE
Plugins needs new contributor

### ISSUE THREAD

**Issue by cctoni** [tim-field/graphql-wp#25]
If theres nothing ongoing progress i would like to take ownership on this plugin and maintain it in the future, because i make a lot of etension like advanced custom fields extension and integrating custom post type calls by default. Plus i'm working on tutorials how to use this plugin for headless systems with vue.js. So please keep me informed if this is possbile.

**Comment by tim-field** [comment]
I don't have projects in active development anymore that are using this plugin, until I do again I won't have much time to add new features. 

Obviously I'm happy to accept pull requests, and if we are on the same page I'll give you write access for sure.
