### ISSUE TITLE
Troubles installing

### ISSUE THREAD

**Issue by alejandropaciotti** [tim-field/graphql-wp#26]
Hello!

I want to install the plugin.

I have successfully installed composer according to instructions in:
Https://getcomposer.org/download/

My wordpress site is installed on:
```shell
/var/www/html/wordpress
```

And I have redirected the entries to that folder:

```shell
<VirtualHost *: 80>
        DocumentRoot /var/www /html/wordpress
        ServerName mydomain.com
        <Directory /var/www/html/wordpress>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow, deny
                Allow from all
        </Directory>
        ErrorLog $ {APACHE_LOG_DIR} /error.log
        CustomLog $ {APACHE_LOG_DIR} /access.log combined
</VirtualHost>
```

I followed the following steps:

```shell
cd  /var/www/html/wordpress
composer require mohiohio/graphql-wp
```

And everything seems to be installed correctly:

```shell
Using version ^ 0.1.3 for mohiohio / graphql-wp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing webonyx / graphql-php (v0.6.4): Loading from cache
  - Installing mohiohio / wordpress-lib (0.1.4): Loading from cache
  - Installing ivome / graphql-relay-php (v0.1.3): Loading from cache
  - Installing mohiohio / graphql-wp (0.1.3): Loading from cache
Writing lock file
Generating autoload files
```

And then I also modified the index.php by adding this line:
```php
require (dirname (__ FILE__). '/vendor/autoload.php');
```

But when I go to my site:

mydomain.com/graphql

I get a 404 error.

**Comment by tim-field** [comment]
Have you got permalinks enabled ? 
Do any other urls work for your site ?

**Comment by henriqueguedes-developer** [comment]
Ola tim I reproduce the scenario that our colleague above did

And for me it is giving error too

My installation

Is in / var / www / html / wp-graph


My composer json is

{
    "Require": {
        "Mohiohio / graphql-wp": "^ 0.4.3"
    }
}


And added in my index.php

require ( dirname( __FILE__ ) . '/wp-blog-header.php' );
require ( dirname (__ FILE__). '/vendor/autoload.php');

My php version

Php -v
PHP 7.0.22-0ubuntu0.17.04.1 (cli) (built: Aug 8 2017 22:03:30) (NTS)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    With Zend OPcache v7.0.22-0ubuntu0.17.04.1, Copyright (c) 1999-2017, by Zend Technologies


In my apache log this error appears


[PHP] Parse error: syntax error, unexpected 'FILE__' (T_STRING), expecting ',' or ')' [Mon Aug 14 19: 27: 17.623136 2017] [: error] [pid 3111] [client :: 1: In /var/www/html/wp-graph/index.php on line 18
PHP Parse error: syntax error, unexpected 'FILE__' (T_STRING), expecting ',' or ')' [Mon Aug 14 19: 28: 01.618379 2017] [: error] [pid 2228] [client :: 1: In /var/www/html/wp-graph/index.php on line 18


I can access the admin of the site without problem, but the pages outside the admin do not work

 I did something wrong, give me a light to light my way I feel lost in this darkness :)

**Comment by shafi49** [comment]
I tried to install this plugin and following error occured 
Fatal error: Uncaught Error: Class 'Mohiohio\WordPress\Router' not found in D:\xampp\htdocs\mySite\wp-content\plugins\graphql-wp-master\index.php:18 Stack trace: #0 D:\xampp\htdocs\mySite\wp-admin\includes\plugin.php(1882): include() #1 D:\xampp\htdocs\mySite\wp-admin\plugins.php(164): plugin_sandbox_scrape('graphql-wp-mast...') #2 {main} thrown in D:\xampp\htdocs\mySite\wp-content\plugins\graphql-wp-master\index.php on line 18

**Comment by tim-field** [comment]
For those that are new to composer, set your project up with https://roots.io/bedrock/
For those that can't get to /graphql/ ensure you have permalinks working, and that other pages can resolve with slugs, i,e /hello-world.  If not then your problem lies with your WordPress install.
For those that are new to WordPress / PHP development, choose your battles ;) this isn't really aimed at a beginner, build a simple WordPress site before using this plugin ;)
