### ISSUE TITLE
Be compatible with PHP 5.6

### ISSUE THREAD

**Issue by geloescht** [tim-field/graphql-wp#28]
There are three instances where graphql-wp uses the ?? operator that could be replaced by ?: in order to be compatible with PHP 5.6 instead of PHP 7:
WPType.php, line 10
Type/Definition/WPPost.php, line 18
Type/Definition/Term.php, line 18

Otherwise I get the following error in the server logs  when trying to access the graphql endpoint:
> AH01071: Got error 'PHP message: PHP Parse error: syntax error, unexpected '?' in ...snip.../wp-content/plugins/graphql-wp/Type/Definition/WPTerm.php on line 18\n'

**Comment by tim-field** [comment]
I'm not keen too keen to do this, as I want to start using more php7 features.
I suspect / hope the crossover of people crazy enough to build a graphpql frontend for WP and yet not want to upgrade to php7 is small :wink: 

http://php.net/supported-versions.php

**Comment by geloescht** [comment]
Well, sadly our server's OS isn't crazy enough to provide PHP7. I understand that if there are any major features of PHP7 that would be beneficial to development of graphql-wp you should utilize them. On the other hand avoiding minor features such as ?? should hurt no one in the meantime. Anyway, I can live with patching those lines.
