### ISSUE TITLE
Version for Nginx

### ISSUE THREAD

**Issue by ghost** [tim-field/graphql-wp#3]
I might do something improperly, but `/graphql` endpoint returns 404 on Nginx.
Everything works ok on Apache2.
Do you receive also 404 on Nginx?

**Comment by tim-field** [comment]
Yeah I use it with nginx, must be something up with your config.  The /graphql endpoint will be handled like any other WordPress rewrite.

**Comment by ghost** [comment]
Did you do something special in Nginx configuration?
I have just installed the fresh copy of Nginx, uncomment the following code in `/etc/nginx/sites_available/default`:

```
location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
}
```

and the `/graphql` endpoint still returns 404.
Wordpress works fine.
Do you have any ideas what I can do?
Cheers.

**Comment by ghost** [comment]
FYI, it seems that I had problems with permalinks. I forgot about them.
