### ISSUE TITLE
Failing OPTIONS requests

### ISSUE THREAD

**Issue by krokofant** [tim-field/graphql-wp#30]
I found that my GraphQL client is sending OPTIONS type requests before every request which silently produces an error.

I think the server endpoint should respond to these requests.

Returning the error:
```json
{"errors":{"message":"Wrong query format or empty query. Either send raw query _with_ Content-Type: 'application\/json' header or send query by posting www-form-data with a query=\"query{}...\" parameter"}}
```

I'd look into the server code myself but I'm not especially crafty with PHP 😜

**Comment by tim-field** [comment]
Thanks I'll take a look, what client are you using ?

**Comment by krokofant** [comment]
@tim-field I used [graphql-request](https://github.com/graphcool/graphql-request)

**Comment by tim-field** [comment]
Should be fixed now 😆
