### ISSUE TITLE
Example Query doesn't work, seems like some of the schema isn't being included?

### ISSUE THREAD

**Issue by roryheaney** [tim-field/graphql-wp#33]
`query example {
 wp_query {
   posts(paged: 1, posts_per_page: 10) {
     title
     name
     terms(taxonomy: "category") {
       name
       slug
     }
   }
 }
}`

returns the following errors:

`{
  "errors": [
    {
      "message": "Unknown argument \"paged\" on field \"posts\" of type \"WPQuery\".",
      "category": "graphql",
      "locations": [
        {
          "line": 3,
          "column": 10
        }
      ]
    },
    {
      "message": "Unknown argument \"posts_per_page\" on field \"posts\" of type \"WPQuery\".",
      "category": "graphql",
      "locations": [
        {
          "line": 3,
          "column": 20
        }
      ]
    },
    {
      "message": "Cannot query field \"title\" on type \"WPPostConnection\".",
      "category": "graphql",
      "locations": [
        {
          "line": 4,
          "column": 6
        }
      ]
    }
  ]
}`

I can see the types are defined inside the plugin, but for some reason, they dont' seem to be registered?

PHP Fatal error: Uncaught Error: Class 'Mohiohio\GraphQLWP\Schema' not found in /app/public/wp-content/plugins/graphql-wp-master/index.php:63

line in question: $schema = Schema::build();

I had installed the plugin, ran composer to include the vendor dependencies.

**Comment by roryheaney** [comment]
I can see the types are defined inside the plugin, but for some reason, they dont' seem to be registered?

**Comment by roryheaney** [comment]
PHP Fatal error: Uncaught Error: Class 'Mohiohio\GraphQLWP\Schema' not found in /app/public/wp-content/plugins/graphql-wp-master/index.php:63

line in question: `$schema = Schema::build();`

**Comment by tim-field** [comment]
Oh yeah sorry, that example is from before this switched to the relay paging format.

Try `first:10` instead.  Also it'll put the result in edges :/ need to update those examples
