### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by graphan** [tim-field/graphql-wp#8]
Hi @tim-field ,

Maybe, I am doing something wrong, but I cannot activate the plugin `mohiohio/graphql-wp`. I receive the following error during activation:

``` php
Plugin could not be activated because it triggered a fatal error.
( ! ) Fatal error: Class 'Mohiohio\WordPress\Router' not found in /var/www/html/wordpress/wp/wp-content/plugins/graphql-wp/index.php on line 18
Call Stack
#   Time    Memory  Function    Location
1   0.2004  243384  {main}( )   .../plugins.php:0
2   0.2900  2458632 plugin_sandbox_scrape( )    .../plugins.php:155
3   0.2901  2459376 include( '/var/www/html/wordpress/wp/wp-content/plugins/graphql-wp/index.php' ) .../plugins.php:153
```

I tried two methods of Wordpress installation: manual and through composer.
I tried also two methods of storing `vendor` folder: inside and outside Wordpress.
Nothing works for me. Do you know what might be the problem?

**Comment by graphan** [comment]
I just found that I had: `"minimum-stability": "dev",` in my `composer.json`.
It was the cause of the problem.

**Comment by graphan** [comment]
Unfortunately, `"minimum-stability": "dev"` was not the cause.
If you could check if it occurs on your side, I would be grateful.

**Comment by graphan** [comment]
Adding:

``` php
require_once __DIR__."/../../../vendor/autoload.php";
```

in `index.php` resolved the problem.

**Comment by luandro** [comment]
Shouldn't this be added to README?

**Comment by tim-field** [comment]
@luandro yeah ok. I guess using composer with WordPress isn't that common, so I've got some basic information in place there. 
You don't want to be doing PHP development without composer these days!

**Comment by heavybeard** [comment]
I have the same problem, and I use composer only for theme. Every plugin that use composer has it's own `require_once __DIR__."/vendor/autoload.php"; `

I've added it on your plugin index.php file and all work like a charm

**Comment by nikolareljin** [comment]
or this:
require_once WP_CONTENT_DIR . "/../vendor/autoload.php";
